---
Name: gisroutes
---
SilverStripe\Control\Director:
  rules:
    'geojsonservice': 'Smindel\GIS\Control\GeoJsonService'
    'webmaptileservice': 'Smindel\GIS\Control\WebMapTileService'
    'webfeatureservice': 'Smindel\GIS\Control\WebFeatureService'
